### ISSUE TITLE
Restore Mimbuild in the interface.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#486] opened 2017-06-19 22:17 UTC
In the config file, this bit of code needs to be uncommented:

            <model name="MIMBuild" acronym="MIMBuild" help="mimbuild"
                   category="Multiple Indicator Model searches">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="details" description="Misc Fine Details" default="on"/>
                    <event id="maxmodel" description="Max P Value Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.MimBuildRunner
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.MimbuildEditor
                </editor-class>
            </model>

**Comment by jdramsey** [comment] 2017-06-19 22:20
@yuanzhou 
@espinoj 

Maybe there's a better interface for Mimbuild, but this one at least works. Here's a screenshot.

<img width="785" alt="screen shot 2017-06-19 at 6 05 03 pm" src="https://user-images.githubusercontent.com/9853255/27308347-fe096368-551b-11e7-8589-b9078220aabd.png">

**Comment by jdramsey** [comment] 2017-06-19 23:42
Also, @ekummerfeld @ps7z

**Comment by yuanzhou** [comment] 2017-06-20 13:22
@jdramsey Do I just uncomment the config section and test things out or is there anything specific you want me to look at?

**Comment by jdramsey** [comment] 2017-06-20 13:28
@yuanzhou I think just uncomment it and try it out, as you say. It should just work; it was working before, and it worked for me just now. I thought it better if you did the honors though, so you weren't surprised.

**Comment by yuanzhou** [comment] 2017-06-20 13:43
@jdramsey no problem. Since I'm also fixing another Tetrad bug, I may combine this issue and the one I'm working on in the same pull request later.

**Comment by jdramsey** [comment] 2017-06-20 13:54
@yuanzhou Great, thanks!

**Comment by yuanzhou** [comment] 2017-06-20 20:07
I was able to get the Mimbuild work. Also noticed the weird highlighting issue that we noticed int he knowledge tier box.

![mim](https://user-images.githubusercontent.com/195873/27353476-25af1ec4-55d2-11e7-8e98-56518a262eab.PNG)
![mm](https://user-images.githubusercontent.com/195873/27353478-2683b4c2-55d2-11e7-9d48-e38909eaf6bb.PNG)

@jdramsey for some reason, I could only get it work once. I tried several times later with multiple searches but just couldn't reproduce. What is the proper procedure to use the Mimbuild?

**Comment by yuanzhou** [comment] 2017-06-20 20:13
For example, I created a data model and imported some data. Then PC search1, FGES search2. On search3, I was able to select "Mimbuild" but it pops up this:

![capture](https://user-images.githubusercontent.com/195873/27353781-478f9126-55d3-11e7-94fd-93ebf69f61f5.PNG)

I think I'll need some instructions on how to use Mimbuild.

**Comment by jdramsey** [comment] 2017-06-20 20:30
Try simulation first.  In the Graph box make a random MIM, with four measures per latent, like this:

<img width="683" alt="screen shot 2017-06-20 at 4 15 28 pm" src="https://user-images.githubusercontent.com/9853255/27353875-b596a7cc-55d3-11e7-8f50-0bd95a0f833b.png">

Do a search, as follows:

<img width="1156" alt="screen shot 2017-06-20 at 4 17 57 pm" src="https://user-images.githubusercontent.com/9853255/27354008-1a9f6d70-55d4-11e7-94ea-5cdd979741ff.png">

Then a measurement model box:

<img width="887" alt="screen shot 2017-06-20 at 4 19 05 pm" src="https://user-images.githubusercontent.com/9853255/27354043-3e1d71d4-55d4-11e7-9b9d-9deb786929be.png">

Then add Mimbuild:

<img width="1226" alt="screen shot 2017-06-20 at 4 21 33 pm" src="https://user-images.githubusercontent.com/9853255/27354137-94a4a496-55d4-11e7-829f-c47835f2ff37.png">

This gives you a graph over the latents.

This is a little difficult to follow for a user; we may need to add an additional pipeline or two for it. Unless you can think of a better way to do it!

**Comment by yuanzhou** [comment] 2017-06-21 16:57
Thanks @jdramsey! I also set the cluster selection to start at 3 with a upper limit of 100. It was showing 0 even though we have 3 clusters, and the upper limit was 1000, which I think is too big. 

I'll send a pull request soon.

**Comment by yuanzhou** [comment] 2017-06-21 20:35
I'm closing this since we've had Mimbuild restored in `development` branch now.

**Closed by yuanzhou** 2017-06-21 20:35 UTC
