### ISSUE TITLE
Knowledge Box

### ISSUE THREAD

**Issue by scheines** [cmu-phil/tetrad#449] opened 2017-06-13 00:46 UTC
Built a 5 variable graph, did a search.  Created a knowledge box - three tiers:
1) X1 X3
2) X2 X4
3) X5

Search executed again, appropriately.   OPened up the Knowledge box to adjust it - found only two tiers, X5 not in either of them - nor in "Not in tier".     Clicked on "Edges" to inspect - clicked back on Tiers tab.  STill only 2 tiers, but now X5 appears in "Not in tier".

**Comment by yuanzhou** [comment] 2017-06-13 04:55
We've noticed some weird behaviors of the knowledge box. This is a duplicate of #440 

After reopening the knowledge box, even though it only shows two tiers, you can change the tier number selection menu and other already added tiers with variables should show up.

**Comment by jdramsey** [comment] 2017-06-13 11:32
Duplicate, closing.

**Closed by jdramsey** 2017-06-13 11:32 UTC
