### ISSUE TITLE
display PM box graph won't show

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#805] opened 2018-06-11 19:57 UTC
Trying to display PM box graph won't show anything after running estimator pipeline.  Shows a triangle exclamation error box.
![screen shot 2018-06-11 at 3 57 07 pm](https://user-images.githubusercontent.com/313721/41254037-21bb7c0a-6d90-11e8-8a21-566ee2f88201.png)

**Comment by espinoj** [comment] 2018-06-13 13:19
This only seems to happen in mac.  Will gather a tet file.

**Comment by espinoj** [comment] 2018-06-13 13:52
stack trace

```
java.lang.IllegalStateException: Could not construct editor
	at edu.cmu.tetradapp.app.TetradApplicationConfig$DefaultModelConfig.getEditorInstance(TetradApplicationConfig.java:551)
	at edu.cmu.tetradapp.app.SessionEditorNode.launchEditorVisit(SessionEditorNode.java:266)
	at edu.cmu.tetradapp.app.SessionEditorNode.access$100(SessionEditorNode.java:90)
	at edu.cmu.tetradapp.app.SessionEditorNode$2.watch(SessionEditorNode.java:239)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:164)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at edu.cmu.tetradapp.app.TetradApplicationConfig$DefaultModelConfig.getEditorInstance(TetradApplicationConfig.java:549)
	... 5 more
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at edu.cmu.tetradapp.workbench.AbstractWorkbench.adjustForNewModelNodes(AbstractWorkbench.java:1220)
	at edu.cmu.tetradapp.workbench.AbstractWorkbench.addNode(AbstractWorkbench.java:1176)
	at edu.cmu.tetradapp.workbench.AbstractWorkbench.access$1100(AbstractWorkbench.java:84)
	at edu.cmu.tetradapp.workbench.AbstractWorkbench$PropertyChangeHandler.propertyChange(AbstractWorkbench.java:2828)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at edu.cmu.tetrad.graph.EdgeListGraph.addEdge(EdgeListGraph.java:1205)
	at edu.cmu.tetrad.graph.SemGraph.addEdge(SemGraph.java:497)
	at edu.cmu.tetrad.graph.SemGraph.addDirectedEdge(SemGraph.java:454)
	at edu.cmu.tetrad.graph.SemGraph.addErrorNode(SemGraph.java:854)
	at edu.cmu.tetrad.graph.SemGraph.adjustErrorForNode(SemGraph.java:911)
	at edu.cmu.tetrad.graph.SemGraph.setShowErrorTerms(SemGraph.java:785)
	at edu.cmu.tetradapp.editor.SemPmGraphicalEditor.<init>(SemPmEditor.java:339)
	at edu.cmu.tetradapp.editor.SemPmEditor.graphicalEditor(SemPmEditor.java:264)
	at edu.cmu.tetradapp.editor.SemPmEditor.<init>(SemPmEditor.java:80)
	... 10 more
java.lang.IllegalStateException: Could not construct editor
	at edu.cmu.tetradapp.app.TetradApplicationConfig$DefaultModelConfig.getEditorInstance(TetradApplicationConfig.java:551)
	at edu.cmu.tetradapp.app.SessionEditorNode.launchEditorVisit(SessionEditorNode.java:266)
	at edu.cmu.tetradapp.app.SessionEditorNode.access$100(SessionEditorNode.java:90)
	at edu.cmu.tetradapp.app.SessionEditorNode$2.watch(SessionEditorNode.java:239)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:164)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at edu.cmu.tetradapp.app.TetradApplicationConfig$DefaultModelConfig.getEditorInstance(TetradApplicationConfig.java:549)
	... 5 more
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at edu.cmu.tetradapp.workbench.AbstractWorkbench.adjustForNewModelNodes(AbstractWorkbench.java:1220)
	at edu.cmu.tetradapp.workbench.AbstractWorkbench.addNode(AbstractWorkbench.java:1176)
	at edu.cmu.tetradapp.workbench.AbstractWorkbench.access$1100(AbstractWorkbench.java:84)
	at edu.cmu.tetradapp.workbench.AbstractWorkbench$PropertyChangeHandler.propertyChange(AbstractWorkbench.java:2828)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at edu.cmu.tetrad.graph.EdgeListGraph.addEdge(EdgeListGraph.java:1205)
	at edu.cmu.tetrad.graph.SemGraph.addEdge(SemGraph.java:497)
	at edu.cmu.tetrad.graph.SemGraph.addDirectedEdge(SemGraph.java:454)
	at edu.cmu.tetrad.graph.SemGraph.addErrorNode(SemGraph.java:854)
	at edu.cmu.tetrad.graph.SemGraph.adjustErrorForNode(SemGraph.java:911)
	at edu.cmu.tetrad.graph.SemGraph.setShowErrorTerms(SemGraph.java:785)
	at edu.cmu.tetradapp.editor.SemPmGraphicalEditor.<init>(SemPmEditor.java:339)
	at edu.cmu.tetradapp.editor.SemPmEditor.graphicalEditor(SemPmEditor.java:264)
	at edu.cmu.tetradapp.editor.SemPmEditor.<init>(SemPmEditor.java:80)
	... 10 more

```

**Comment by espinoj** [comment] 2018-06-13 13:53
[805.tet.zip](https://github.com/cmu-phil/tetrad/files/2098383/805.tet.zip)

**Comment by jdramsey** [comment] 2019-04-06 23:59
@kvb2univpitt  I think I can fix this by iterating over a copy of the nodes in the foreach there.

Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at edu.cmu.tetradapp.workbench.AbstractWorkbench.adjustForNewModelNodes(AbstractWorkbench.java:1220)

That is, change this:

       this.graph.getNodes().forEach(node -> {
 
to this:

      new ArrayList<>( this.graph.getNodes()).forEach(node -> {

in line 1206 of AbstractWorkbench.

**Comment by jdramsey** [comment] 2019-04-09 13:23
@kvb2univpitt @espinoj Wait, this is fixed! I just tried it! On a mac. I think this can be closed..?

**Comment by kvb2univpitt** [comment] 2019-04-24 18:55
@jdramsey I fixed this a while back.  I'll close it.

**Closed** 2019-04-24 18:55 UTC
Labels: bug

**Comment by jdramsey** [comment] 2019-04-24 19:17
Thanks!
