### ISSUE TITLE
Rename: Work on gadget to compare search outputs from multiple platforms.

### ISSUE THREAD

**Issue by magical-hhc** [cmu-phil/tetrad#1594] opened 2023-04-29 08:20 UTC
Many social network analysis are based on the results of Granger causality test. If it is replaced by the results of causality test on tetrad, what impact will it have on the results of social network analysis? Will it be better or worse? I'm a little curious!

**Comment by jdramsey** [comment] 2023-04-29 08:44
Oh, that's an interesting question! It depends on the algorithm you pick and the score or test for either. Granger causality is equivalent to, say, PC with defined temporal tiers; it's just that the conditioning is done in a slightly different order. For more accuracy, you could use GRaSP with temporal tiers--the current version of Tetrad fixes the use of knowledge with GRaSP, so this is plausible. Or BOSS with temporal tiers if you want to use the experimental algorithms; the use of temporal tiers with BOSS is much improved--hopefully, we'll put that in print soon. So I'd be interested in a performance comparison between the best Granger causality software and, say, BOSS with temporal tiers or even SP with temporal tiers (which is possible now). I may make a comparison like that at some point, though I still need to do it. The short answer, though, is the methods are equivalent, so it depends on which way is giving the leg up in practice. It's unfair to say one or the other is better without comparing specific choices.

I've been working toward a way to quickly compare causal searches across platforms, languages, and projects. If I'm successful in this, it should be possible to give a good, quantifiable answer to your question.

(You can see that I'm hesitant to say one way or the other without specific evidence! Sorry.)

**Comment by magical-hhc** [comment] 2023-04-29 09:52
Thank you for thinking about my problem seriously, which is what I suddenly thought when studying social network analysis.
How to compare the two causal tests and distinguish the advantages and disadvantages of both parties is a problem worth studying. As you said, there is no good platform and method to test at present. If your team can find an effective way to complete this, it should be a milestone breakthrough for tetrad!

**Comment by cg09** [comment] 2023-04-29 16:18
There is no one "causality test" in TETRAD. There are a bunch, according to
the problem.  But for linear, Gaussian systems for which Granger was
designed, there are some practical problems with Granger.  If the true
speed of causal connection is much faster than the sampling rate, Granger
finds (some) false connections. Because Granger is linear regression for
time indexed variables and there are unobserved confounders, Granger also
finds some false connections, even for variables that are not themselves
directly affected by a common unobserved cause. And Granger requires that
the time series be stationary. There is a time series algorithm in TETRAD
due to Huang and Zhang that does not require linearity (although there must
be a linear component) and does not require stationarity (theoretically).
For non-Gaussian time series there is an algorithm, FASK, which showed
excellent behavior on non-stationary, linear (ish) fMRI time series--which
are not Gaussian.

**Comment by jdramsey** [comment] 2023-05-11 19:58
@magical-hhc I was rereading your response. Yeah, that is something I want to do, and I want to do it so that people can compare the new algorithms they make (which are becoming more common now) to existing algorithms relatively quickly, with particular goals in mind. You want to find the best algorithm for the job, and it's hard to tell this from reading the experimental sections of papers, which may be comparing the wrong set of algorithms on problems you don't care about. Even though our code is in Java, we have a Python wrapper now. I think Python is a good "Roman language" for this, Roman in the sense that it allows access to a wide range of programmatic "belief systems" in that you can access Java, Matlab, R, Rust, Julia, and other languages from it to make the comparisons. I've wanted to do something like that and have been planning and plotting my way toward it.

By the way, anyone else reading this, if you have ideas, let us know.

**Comment by cg09** [comment] 2023-05-12 01:09
Isn't that what Bryan's comparison algorithm is for?

**Comment by jdramsey** [comment] 2023-05-12 06:45
You mean algcomparison in Tetrad? That's my comparison algorithm, but honestly Bryan has made the most use of it lately, in addition to writing his own comparison code in Python. But yeah, that's the sort of thing I have in mind, but expanded to allow easy inclusion of various projects. Kevin Bui wrote a command-line wrapper for this; we published it in JMLR here:

Ramsey, J. D., Malinsky, D., & Bui, K. V. (2020). algcomparison: comparing the performance of graphical structure learning algorithms with TETRAD. The Journal of Machine Learning Research, 21(1), 9649-9654.

He gives (at the insistence of the reviewers) a method to include graphs generated by other algorithms, in Tetrad format, which we could use. I had the thought to write methods in Python to do translations into Tetrad-style algorithms from various methods, which would allow us to use Kevin' tool. I started doing this but got pulled away from it. It's worth doing in my view, though; we could compare all CPDAG and PAG algorithms that way. That would be helpful already. I'm still planning to do this.

**Comment by jdramsey** [comment] 2023-05-12 06:55
One nice features of algcomparison is that you can easily include whatever statistics you want in tables, so long as they're implemented, and it's not easy to write more ones. In fact, through the magic of JPype (see our Python project, [py-tetrad](https://github.com/cmu-phil/py-tetrad)), it's pretty easy to write new ones _in Python!_ and include them in the tables, despite the tool being written in Java. Bryan figured out how to do this with scores, super nice. I hadn't thought of that until just now. :)

This is a boon, since when you're comparing projects for. a particular goal you have in mind, you may sincerely want to compare algorithm using statistics other than the ones authors used to compare things in their experimental sections of their papers. For instance, you may care honestly more about BIC scores than anything else, so if the author didn't include a BIC comparison, you're toast. You have no idea which algorithm to prefer. The idea of the above is that you'd be able to make a table for their algorithm plus others and see which ones gives you the best BIC score for the problems you have in mind.

**Comment by cg09** [comment] 2023-05-12 13:56
The chance authors of papers will include their data is close to zero.

**Comment by MikeKonrad** [comment] 2023-05-12 15:09
I’m happy to report some authors are (including yours truly). I’ll wait to see if the article is accepted for publication before saying more.

**Comment by cg09** [comment] 2023-05-12 17:55
Mike,

I attach some answers (I think!) to your question.

Clark

**Comment by jdramsey** [comment] 2023-05-27 17:03
Let me take this one up. OK, I aim to save the B matrix for a DAG estimated using the SEM estimator. Of course we need to save the exogenous variances as well. Maybe this format?

Variables:

a d f s 

Exogenous variances:

a b c d e...

B Hat:

a 0  0. 0 ...
b d.  0  f ...
0  e
...

**Comment by jdramsey** [comment] 2023-05-27 17:38
OK, in the development branch I've added menu items to SEM IM Editor and SEM Estimator Editor to copy the coefficient (B Hat) matrix and the error covariance matrix to the clipboard. You can then paste them in a text file.

That's the fix I was intending to do for this, and I was the one requesting the issue to stay open, so I'll close it but @magical-hhc open it back up if it wasn't what you intended.

This is in the development branch now and will be published in the next publish cycle.

**Comment by jdramsey** [comment] 2023-05-27 17:40
Oh sorry I closed the wrong issue. Let me re-open this and move the above comments to the other issue and close it.

**Closed** 2023-08-03 17:50 UTC
