### ISSUE TITLE
Time lag graphs to generalized SEM PMs

### ISSUE THREAD

**Issue by mglymour** [cmu-phil/tetrad#1005] opened 2019-03-26 20:17 UTC
Attempting to input a time lag graph to a generalized SEM PM results in a blank error message (in 6.7.0-0)

**Comment by kvb2univpitt** [comment] 2019-03-26 20:22
I haven't worked with time lag graph.  Is it supposed to complain when you do that?  If so, what should the error message be?

**Comment by mglymour** [comment] 2019-03-26 20:31
I don't think so. I can't see any reason why a time lag graph shouldn't be able to be input to a generalized SEM PM -- they should be able to have nonlinear, non-Normal relations, which is what generalized SEM PMs are for, and they only use directed edges, which is the only requirement I know of for generalized SEM PMs. And although I can't specifically remember whether this was the case, the wording of the manual makes me think that when I wrote it, time lag graphs could be input into generalized SEM PMs.

But Jeremy or Joe might have more insight into this.

**Comment by kvb2univpitt** [comment] 2019-03-26 20:33
Ok.  We'll wait for @espinoj  and @jdramsey input on this before I jump into it.

**Comment by jdramsey** [comment] 2019-03-26 20:48
What causes the blank error message? Is it something dumb?

**Comment by mglymour** [comment] 2019-03-26 20:57
Possibly, but I don't think so. I created the simplest possible time lag graph (one variable, one lag, one edge) and tried to put it into a generalized SEM PM, and it won't let me. No matter what time lag graph I create, it won't let me.

**Comment by kvb2univpitt** [comment] 2019-03-27 15:08
@mglymour Can you please attach a session file for this?  Thanks.

**Comment by mglymour** [comment] 2019-03-27 17:02
Github is not allowing me to attach a .tet file, so I'll email it to you.

**Comment by kvb2univpitt** [comment] 2019-03-27 17:18
@mglymour It works for me.  I am using the version from the development branch.  What version are you using?
![lag](https://user-images.githubusercontent.com/10729309/55097687-bdb95d80-5092-11e9-8f8c-f651c337e02a.png)

**Comment by cg09** [comment] 2019-03-27 17:41
Doesn't work for me either. We are using 6.7.0-0.
[image: Screen Shot 2019-03-27 at 1.40.02 PM.png]

**Comment by kvb2univpitt** [comment] 2019-03-27 18:07
@cg09 Clark, I can't see your attached screenshot.  Can you please email it to me or attach via github website instead of replying it through email?  Thanks.

**Comment by chirayukong** [comment] 2019-03-27 18:13
<img width="909" alt="Screen Shot 2019-03-27 at 2 11 32 PM" src="https://user-images.githubusercontent.com/4652250/55101392-64552c80-509a-11e9-9ba1-9654f68ed251.png">
I can run it on my iMac as well.

**Comment by kvb2univpitt** [comment] 2019-03-27 18:17
Also works in Windows 7.

![timelag_win](https://user-images.githubusercontent.com/10729309/55101642-f8bf8f00-509a-11e9-9b62-2472177cbd6a.PNG)

**Comment by mglymour** [comment] 2019-03-27 18:58
It's possible this is a Mojave vs. High Sierra issue on Macs. We've run into a couple of those elsewhere in the program. I'll update tonight and see if it's still turning up tomorrow.

**Comment by kvb2univpitt** [comment] 2019-03-27 19:15
@mglymour Please keep us posted.  While you're at it, can you please test previous issues you were having?  If the issues go away after you updated your MAC, please close them.  Thanks.

**Comment by cg09** [comment] 2019-03-27 22:05
Kevin,

Attached. It was the same as Madelyn's error. I am running OS El Capitan.
She runs High Sierra, I think. Joe runs Mojave. Surely, a program should
not be so sensitive to operating systems??

Clark

**Comment by jdramsey** [comment] 2019-03-27 22:20
@cg09 It occurred to me there may be a virus involved or something. The OS's are pretty old at this point.

**Comment by mglymour** [comment] 2019-03-27 22:28
I just updated to Mojave and I am still getting the error.

**Comment by cg09** [comment] 2019-03-27 22:38
Virus is possible, although it has an odd way of showing up. I am running a
full scan on my computer.

**Comment by cg09** [comment] 2019-03-27 22:40
Try updating your JAVA.

**Comment by mglymour** [comment] 2019-03-27 22:45
I have updated Java as much as possible; the error persists.

**Comment by cg09** [comment] 2019-03-27 23:15
Maybe Joe and Joe are using different versions of TETRAD? Ramsey sometimes
uses his private version without telling us.

**Comment by jdramsey** [comment] 2019-03-27 23:48
@kvb2univpitt @cg09 @mglymour 

I think I see the issue. In GeneralizedSemPm, replace line 248:

        this.variableNames = new ArrayList<>();
        for (Node _node : variableNodes) variableNames.add(_node.getName());
        for (Node _node : errorNodes) variableNames.add(_node.getName());

with thisP

        this.variableNames = new ArrayList<>();
        for (Node _node : variableNodes) variableNames.add(_node.getName());

        for (Node _node : errorNodes) {
            if (_node != null) {
                variableNames.add(_node.getName());
            }
        }

For those who don't read code, the issue is that the error terms are being added to the list of variables, but for lag graphs (this specific graph type, not ones you make in the graph editor with :1's added to the variables names), lag 2 variables don't have error terms. It's a *lag* graph, a repeating structure; in the sliding window, the error terms are always for the *current* time lag, that is, the time lag for the position of the sliding window,  all other variables being parents of those. As place-holders, error terms for the lag 1 and lag 2, etc., variables are recorded as "null". When a list of all variable names is constructed, these null's shouldn't be included--they're not variables; they have no names.

**Comment by jdramsey** [comment] 2019-03-27 23:56
@kvb2univpitt @cg09 @mglymour 

Here's how to reproduce the issue (I think). Put a Graph box on the workbench, double click, and select Lag Graph. Make a lag graph. Close the window. Then make a PM box, connect the Lag Graph box to it, and double click. With the existing code, you will see the unhelpful error box Madelyn said was there. With my fix, you don't and the PM opens up correctly.

**Comment by jdramsey** [comment] 2019-03-28 00:18
@kvb2univpitt @cg09 @mglymour 

The lag graph I made had two guys in lag 0, with one lag, like this:

<img width="780" alt="Screen Shot 2019-03-27 at 8 17 57 PM" src="https://user-images.githubusercontent.com/9853255/55120705-743a3400-50cd-11e9-8c07-4e67defd7880.png">

**Comment by cg09** [comment] 2019-03-28 01:05
Joe, you are a genius. Please push your fix.

**Comment by kvb2univpitt** [comment] 2019-03-28 01:56
@mglymour @cg09 @jdramsey That is exactly what I did when I first tested it.  I wasn't able to reproduce the error.  Thus, I asked Madelyn to give me her session.  I was still not able to reproduce the error.  As the matter of fact, I still can't reproduce the error.

![lag](https://user-images.githubusercontent.com/10729309/55123920-d483a280-50da-11e9-9677-2c64405eb962.png)

Joe, can you please push your changes?  I can't verify if anything works on my end since I can't produce that error.

**Comment by jdramsey** [comment] 2019-03-28 02:26
Oh boy. I'm in a very different branch that I cannot in all conscience push. Let me clone development and see if I still get the error.

**Comment by jdramsey** [comment] 2019-03-28 02:41
OK, I'm pushing it. I pulled from development, checked to make sure I got the error, made the change, checked to make sure the fix was made, and committed, pushed the result and made a ull request, this one:

https://github.com/cmu-phil/tetrad/pull/1006

I made screen shots.

<img width="718" alt="Screen Shot 2019-03-27 at 10 37 21 PM" src="https://user-images.githubusercontent.com/9853255/55125839-5d054180-50e1-11e9-8a7f-cf9e1e25d9e6.png">
<img width="558" alt="Screen Shot 2019-03-27 at 10 35 22 PM" src="https://user-images.githubusercontent.com/9853255/55125840-5d054180-50e1-11e9-897d-f34c5ebc37f3.png">
<img width="1" alt="Screen Shot 2019-03-27 at 10 35 18 PM" src="https://user-images.githubusercontent.com/9853255/55125841-5d054180-50e1-11e9-8e8c-33d824279201.png">
<img width="736" alt="Screen Shot 2019-03-27 at 10 35 11 PM" src="https://user-images.githubusercontent.com/9853255/55125842-5d9dd800-50e1-11e9-9b38-cba692058851.png">
<img width="562" alt="Screen Shot 2019-03-27 at 10 34 59 PM" src="https://user-images.githubusercontent.com/9853255/55125843-5d9dd800-50e1-11e9-9cfc-24554cd9460f.png">

**Comment by jdramsey** [comment] 2019-03-28 02:43
Sorry, @mglymour @cg09 @kvb2univpitt 

Not a genius. Kevin's machine may be different. See previous comments for details.

**Comment by kvb2univpitt** [comment] 2019-03-28 03:14
@mglymour Can you please check out the branch **"possible_time_lag_general_sem.fix_we'll_see"** and see if it works for you?  I will approve the pull request once you verify that it works.  Thanks.

**Comment by mglymour** [comment] 2019-03-28 03:40
It works!

**Closed** 2019-03-28 04:07 UTC
