### ISSUE TITLE
AdjacencyConfusion calculation problem for different objects

### ISSUE THREAD

**Issue by huiouyang16** [cmu-phil/tetrad#1551] opened 2023-03-15 12:57 UTC
I'm trying to use the class [AdjacencyConfusion](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/statistic/utils/AdjacencyConfusion.java) to perform statistical calculations on my two graphs (nodes with the same name, but different objects). However, the expected calculation results were not obtained.

By checking the code, I found that the problem is in the class [EdgeListGraph](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/graph/EdgeListGraph.java), where the method [`isAdjacentTo`](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/graph/EdgeListGraph.java#L408) [[line 415]](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/graph/EdgeListGraph.java#L415) uses `==` when comparing whether the nodes are equal, instead of the method `equals`.

In the class [GraphNode](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/graph/GraphNode.java), the method [`equals`](https://github.com/cmu-phil/tetrad/blob/development/tetrad-lib/src/main/java/edu/cmu/tetrad/graph/GraphNode.java#L226) is overridden. In this override method, the javadoc says "Two continuous variables are equal if they have the same name and the same missing value marker". Based on this, I think the original intention of the comparison is to compare whether the names are equal, not whether they are the same object. However, `==` in Java directly compares whether the addresses of two objects are equal.

----------

Thus, for the calculation of AdjacencyConfusion, my question is:

**the original intention is that only the node names in the two graphs are equal, but "==" is used incorrectly.**

or

**this method itself requires that the nodes in the graph truth and est be the same object, not just the same name.**

----------

For example:

```
import edu.cmu.tetrad.graph.*;
import edu.cmu.tetrad.algcomparison.statistic.utils.AdjacencyConfusion;

import java.util.ArrayList;

public class main {

    public static void main(String[] args) {
        ArrayList<Node> nodesA = new ArrayList<>();
        nodesA.add(new GraphNode("node0"));
        nodesA.add(new GraphNode("node1"));
        nodesA.add(new GraphNode("node2"));
        EdgeListGraph graphA = new EdgeListGraph(nodesA);
        graphA.addDirectedEdge(nodesA.get(0), nodesA.get(1));
        graphA.addUndirectedEdge(nodesA.get(1), nodesA.get(2));

        ArrayList<Node> nodesB = new ArrayList<>();
        nodesB.add(new GraphNode("node0"));
        nodesB.add(new GraphNode("node1"));
        nodesB.add(new GraphNode("node2"));
        EdgeListGraph graphB = new EdgeListGraph(nodesB);
        graphB.addDirectedEdge(nodesB.get(0), nodesB.get(1));
        graphB.addUndirectedEdge(nodesB.get(1), nodesB.get(2));

        AdjacencyConfusion ac = new AdjacencyConfusion(graphA, graphB);
        System.out.println(ac.getTp());
        System.out.println(ac.getFn());
    }
}

```

`graphA` and `graphB` are graphs with same structure (nodes with **same names, but different objects**). According to my requirement, I want the output should be 2 (tp) and 0 (fn), but actually the output is 0 (tp) and 2 (fn).

If I change the code, both graphs use nodes from the **same object**, 

```
import edu.cmu.tetrad.graph.*;
import edu.cmu.tetrad.algcomparison.statistic.utils.AdjacencyConfusion;

import java.util.ArrayList;

public class main {

    public static void main(String[] args) {
        ArrayList<Node> nodesA = new ArrayList<>();
        nodesA.add(new GraphNode("node0"));
        nodesA.add(new GraphNode("node1"));
        nodesA.add(new GraphNode("node2"));
        EdgeListGraph graphA = new EdgeListGraph(nodesA);
        graphA.addDirectedEdge(nodesA.get(0), nodesA.get(1));
        graphA.addUndirectedEdge(nodesA.get(1), nodesA.get(2));

        EdgeListGraph graphB = new EdgeListGraph(nodesA);
        graphB.addDirectedEdge(nodesA.get(0), nodesA.get(1));
        graphB.addUndirectedEdge(nodesA.get(1), nodesA.get(2));

        AdjacencyConfusion ac = new AdjacencyConfusion(graphA, graphB);
        System.out.println(ac.getTp());
        System.out.println(ac.getFn());
    }
}
```

the output is correct.

----------

Maybe the original intention of the code is to require the node objects of the two graphs to be the same, but this is a bit strange. When you use the algorithm to learn a **graph est**, and then load another **graph truth** from the file system, it is difficult for you to guarantee that their node objects are identical.

**Comment by jdramsey** [comment] 2023-03-15 14:12
We had situations where we needed either one behavior or the other, so we added a class, NodeEqualityMode, which allows you to get the behavior you're seeking. The idea is to type this:

NodeEqualityMode.setEqualityMode(NodeEqualityMode.Type.OBJECT);

Then equality will be assessed the way you're hoping. Do you think this is helpful at all?

If so, I'll try to add some better comments for this.

**Comment by jdramsey** [comment] 2023-03-15 14:22
I agree, though; the difficulty is exactly what you say--another "trick" we have for dealing with this situation is to use GraphUtils.replaceNode(.) to ensure the nodes are object-identical between two graphs if they are named the same--e.g.:

G = GraphUtils.replaceNodes(G, G0.getNodes())

Now, G and G0 will have object-identical nodes.

I've often wanted to go back and enforce a policy that all nodes named, say, "X" will be the same object, perhaps using a static map from names to nodes. The problem is that people in the interface wanted to make different graphs with variables named "X" that had different properties--say, one was continuous and the other discrete. But forcing the user to choose a new variable name in that context would also solve the problem. What do you think? We could refactor and simplify a lot of code that way, which in my mind, is a good thing, though I'd have to convince others to do along with it. For one thing, node equality could just object equality, as you say, unproblematically.

**Comment by jdramsey** [comment] 2023-03-15 14:33
By the way, that is a refactoring I'd be willing to do, and it wouldn't be all that difficult, TBH, thinking about it. It may be time for it at this point. It would solve as you say an outstanding problem.

**Comment by jdramsey** [comment] 2023-03-15 14:38
The only downside is that you would no longer be able to find a graph over continuous nodes and a graph over discrete nodes to be equal graphs just because the edges connecting nodes of the same name are identically arranged. You would need to first substitute the same variables throughout to do that. But I don't think that is insurmountable. A graph, after all, theoretically, should be a set of nodes over which a group of edges is defined, and those two graphs (the one with continuous nodes and the other with discrete nodes) should be counted as different.

**Comment by jdramsey** [comment] 2023-03-15 18:25
@huiouyang16 I talked about refactoring with @bja43  and @kvb2univpitt, and we all think it makes sense. It's a large and deep refactoring in the code, but it will clarify things. Certainly, it will solve your problem. But like I said, not for the upcoming release but for the release after that.

The idea will be to distinguish nodes from variables in the code so that this kind of confusion can't come up, and to enforce the rule that variables with the same name are object-identical.

**Comment by cg09** [comment] 2023-03-15 19:06
And it will produce new bugs...I bet.

**Comment by jdramsey** [comment] 2023-03-15 20:16
@cg09 I will do my best :) If I can't make it work, I'll revert the code. I
can use the IntelliJ refactoring tools.

**Comment by huiouyang16** [comment] 2023-03-16 06:41
Refactoring code is indeed a way to solve this problem from the architectural level, but it may indeed bring new problems, for example: in the same program, I may need to constantly switch between different mode, which is easy to cause other bugs.

A possible solution is to add a new parameter to the relevant methods, allowing the user to decide whether to use content comparison or object comparison.

But anyway before that, I think `G = GraphUtils.replaceNodes(G, G0.getNodes())` is a good transition solution.

**Comment by jdramsey** [comment] 2023-03-18 22:28
@huiouyang16 I'll think it through before going anything and clarify the advantages and disadvantages. In any case, I will wait to do anything until after next week.

**Comment by jdramsey** [comment] 2023-03-24 03:49
@huiouyang16 Hmm... now I share your trepidation about the node/variable refactor. I'll put it off for a while since you say the other solutions are working OK.

**Comment by huiouyang16** [comment] 2023-03-24 06:18
> @huiouyang16 Hmm... now I share your trepidation about the node/variable refactor. I'll put it off for a while since you say the other solutions are working OK.

Yep, I have used another form to complete the function I want to achieve (I call Tetrad on python through JPype, and I wrote a wrapper myself to make the objects of the two compared graph nodes the same). So you can wait to fix this until you want (or think of a particularly good way), lol.

**Comment by jdramsey** [comment] 2023-04-13 14:47
Hi @huiouyang16 Can I close this issue? I'll remember and think about the node/variance refactoring I talked about, but it looks like your particular problem has been solved... ?

**Comment by jdramsey** [comment] 2023-04-17 14:07
Thanks, closing :)

**Closed by jdramsey** 2023-04-17 14:07 UTC
