### ISSUE TITLE
GRaSP is oriented edges in triangles that should be unoriented

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#1467] opened 2023-01-27 22:37 UTC
See title... perhaps there is an issue with DAG -> CPDAG?

**Comment by jdramsey** [comment] 2023-01-27 22:55
This should be solved by issue 1 in the forthcoming issues list. If need be I can post a revision sooner rather than later to fix this.

https://github.com/cmu-phil/tetrad/wiki/Forthcoming-fixes-for-7.1.3_2

**Comment by jdramsey** [comment] 2023-02-05 05:40
Let me test what I think the problem is here...

**Comment by jdramsey** [comment] 2023-02-05 05:44
This is fixed. I'll close it. I make triangles in DAGs and give these to BOSS to analyze using dsep and it doesn't put the extra orientations in when return the CPDAG. Closing.

**Closed by jdramsey** 2023-02-05 05:44 UTC
