### ISSUE TITLE
Spaces and ampersands when resampling leading to non-specific errors

### ISSUE THREAD

**Issue by jraysajulga** [cmu-phil/tetrad#1382] opened 2022-04-20 21:44 UTC
Column names containing spaces and/or ampersands when resampling lead to non-specific errors.

**Comment by jdramsey** [comment] 2022-04-20 21:47
Can you give me some examples of your column names? Also, can you eliminate the problem by renaming the variables?

**Comment by jraysajulga** [comment] 2022-04-20 21:48
Thanks for the quick response. The dataset is semi-public so I'm not sure I can give the exact names, but they contain spaces and ampersands.

Luckily, the problem is eliminated when the spaces and ampersands are taken out. This is just for your record, in case you wanted to address this tiny bug.

**Comment by jdramsey** [comment] 2022-04-20 21:56
Thanks. You know, at least if spaces and ampersands aren't allowed I could tell people that. That helps.

**Comment by jraysajulga** [comment] 2022-04-20 22:02
Exactly. No problem! Thanks for all of your work on this program!

**Comment by jdramsey** [comment] 2022-04-23 15:25
BTW thanks for the kind comment!

**Comment by jdramsey** [comment] 2023-01-19 22:01
@jraysajulga Getting back to thinking about this. Sorry so slow. Here's the regex for variable names: "[^0-9]?[^ \t]*". So spaces and ampersands are definitely being excluded. Hold on, I see what the problem is. Internal parsing in some parts of Tetrad like the generalized SEM PM would be totally messed up if those characters were there. So we can't have those characters in the names. Let me talk with @kvb2univpitt  to see if applying the variable name regex in data parsing would help to give better feedback about this.

**Comment by kvb2univpitt** [comment] 2023-01-29 19:28
Spaces and ampersands are allowed in variable names, as you can see here:

![Screenshot from 2023-01-29 14-00-17](https://user-images.githubusercontent.com/10729309/215349631-a8852051-7d39-4914-b585-c8c6b9f23af1.png)

Spaces and ampersands are also allowed in the data.  I simulated a discrete dataset and created two copies of the same dataset.  In the sim_discrete_10var_1kcase.txt, I replace the variable names with ones that has spaces and ampersands.  The sim_cat_discrete_10var_1kcase, I keep the original variable names and just replace the data with values that have both spaces and ampersands.  Since both data are technically the same, the search returns the same graph structure for the variables.

![Screenshot from 2023-01-29 14-28-23](https://user-images.githubusercontent.com/10729309/215351040-bdc179e5-1535-469e-824c-185138a70cc3.png)

Example data:
[sim_discrete_10var_1kcase.txt](https://github.com/cmu-phil/tetrad/files/10530628/sim_discrete_10var_1kcase.txt)
[sim_cat_discrete_10var_1kcase.txt](https://github.com/cmu-phil/tetrad/files/10530630/sim_cat_discrete_10var_1kcase.txt)

**Comment by jdramsey** [comment] 2023-02-02 17:26
Thanks @kvb2univpitt I think @jraysajulga  is offline now so I'll close this. @jraysajulga if you have further questions, please re-open this issue. -JR

**Closed by jdramsey** 2023-02-02 17:26 UTC
