### ISSUE TITLE
Missing bootstrap parameters

### ISSUE THREAD

**Issue by bja43** [cmu-phil/tetrad#1454] opened 2023-01-19 18:57 UTC
In the GUI, the bootstrap parameters of some searches are sometimes missing. I am not sure how to recreate this issue, it seems to happen randomly.

**Comment by kvb2univpitt** [comment] 2023-01-23 04:22
Can you please take a screenshot the next time you encounter it?

**Comment by jdramsey** [comment] 2023-02-08 21:11
Unable to reproduce. Closing.

**Closed by jdramsey** 2023-02-08 21:11 UTC
