### ISSUE TITLE
Tetrad is not loading any data

### ISSUE THREAD

**Issue by Shreeja7Sheth** [cmu-phil/tetrad#1517] opened 2023-02-13 11:23 UTC
Tetrad gui version 7.1.3  is not loading any kind of data. I tried loading a csv file of 7kb and 800kb. Nothing happens. Please help.

**Comment by jdramsey** [comment] 2023-02-13 11:32
What type of machine are you on?

**Comment by jdramsey** [comment] 2023-02-13 11:36
Also, just to let you know, we did release a version back in January with many updates--instructions for download are here:

https://sites.google.com/view/tetradcausal/faq

We're planning to release another update any day now, maybe today or tomorrow.

**Comment by jdramsey** [comment] 2023-02-13 11:37
Also wondering, which version of Java do you have?

**Comment by jdramsey** [comment] 2023-02-13 11:59
Also, could you send me one of the files you're trying to load to see if I can load it?

**Comment by Shreeja7Sheth** [comment] 2023-02-13 13:11
I have downloaded jre-8u361 and my computer is 64-bit and I am using a windows PC.

**Comment by jdramsey** [comment] 2023-02-13 13:24
I see, so the data starts out like this:

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
0,27,177119,10,0,0,44
1,27,216481,13,0,0,40
2,25,256263,12,0,0,40
3,46,147640,3,0,1902,40
4,45,172822,7,0,2824,76

The problem is that the first column, which is unnamed, is an index column, so either you have to give it a name in the dataset like this:

Index,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
0,27,177119,10,0,0,44
1,27,216481,13,0,0,40
2,25,256263,12,0,0,40
3,46,147640,3,0,1902,40
4,45,172822,7,0,2824,76

or else, when you're loading in the data, for "Case columns to exclude/ignore", select "First column"--then it will load, though without the index column.

Usually, index columns are nuisance information that doesn't have anything to do with causal analysis. They're just numbering the cases so you can look up a row more easily. So ignoring them is fine, Sometimes though they contain temporal information, in which case they might be helpful in some analyses. I don't know which case is here.

**Comment by jdramsey** [comment] 2023-02-13 13:29
Actually if you're interested, I put the original 'adult' dataset in a repository here:

https://raw.githubusercontent.com/cmu-phil/example-causal-datasets/main/real/adult/data/adult.data.mixed.numeric.txt

it's got both continuous and discrete columns, so the analysis has to be different, and loading it can be difficult. Let me know if you're interested and I can tell you how to do it.

**Comment by Shreeja7Sheth** [comment] 2023-02-13 13:34
Yes its solved thanks. I had downloaded just jre instead of a jdk and that's why it was not working. Thanks it works now.

**Comment by Shreeja7Sheth** [comment] 2023-02-13 13:46
but then how to choose which algorithm to apply for our data?

**Comment by jdramsey** [comment] 2023-02-13 14:35
On this data? Well, this version of the data leaves out most of the variables, so one of the algorithms that ends with "FCI" I'd guess...

**Comment by jdramsey** [comment] 2023-02-14 12:49
Sorry, I was not feeling very well yesterday... let me know if you still need help with this; the issues can be a bit complicated.

**Comment by jdramsey** [comment] 2023-02-17 16:24
Hi @Shreeja7Sheth I assume your issue is fixed, so I'll close the issue, but if it's not, please re-open it and add more comments. Cheers -Joe

**Closed by jdramsey** 2023-02-17 16:24 UTC
