### ISSUE TITLE
Missing options in Estimator Node

### ISSUE THREAD

**Issue by mdibiase1** [cmu-phil/tetrad#1349] opened 2021-09-14 10:36 UTC
Hi there,

I am using version 6.9.0. When using the estimator node, sometimes most of the options (Graphical Editor, Tabular Editor, Implied Matrices, and Model Statistics) do not appear (see attached screenshot). Also, the options that are usually displayed on the bottom (score, done, etc) do not appear, so the only way to close the estimator pop up box is to close the Tetrad session. I think this happens when my data contains more than 60 variables; however I am not sure if this is the reason. 

<img width="1463" alt="Screen Shot 2021-09-14 at 8 27 36 PM" src="https://user-images.githubusercontent.com/49312332/133241627-736c90bb-617c-40a1-b4a4-56de6407a9f5.png">
](url)

Your help would be greatly appreciated. 

Thanks,

Maria

**Comment by jdramsey** [comment] 2021-09-21 06:41
Is it possible that the display has become very large so that the controls are off screen for that reason? If so, perhaps we could limit the size o that window?

**Comment by jdramsey** [comment] 2022-02-25 16:54
Puzzling over this now.

**Comment by jdramsey** [comment] 2022-02-25 16:56
I can't reproduce the problem. Let me come back to it

**Comment by jdramsey** [comment] 2022-03-08 23:21
I still can't reproduce the problem. I'm going to close it for now but if you're still having trouble please reopen it.

**Closed by jdramsey** 2022-03-08 23:21 UTC
