### ISSUE TITLE
comparison of graphs incorrect?

### ISSUE THREAD

**Issue by eberharf** [cmu-phil/tetrad#505] opened 2017-08-18 22:48 UTC
When I "Compare" two graphs and select "Tabular Comparison" a dialog box opens asking me to select the "true" graph. If I indeed select the true graph, then precision and recall will be calculated incorrectly in the following tables: it seems to generally (though strangely not always) select the estimated graph, resulting in AP and AR values of 1, when I can see that the output of the search is different from the generating graph.

version 6.3.4 jar downloaded a few days ago

**Comment by eberharf** [comment] 2017-08-30 23:43
The above problem appears to arise when one has multiple "runs" in the Simulation.

**Comment by jdramsey** [comment] 2018-01-31 16:01
@eberharf I can't reproduce this. It is possible that it's comparison to the pattern (as it would for PC, FGES, etc.) and not the true DAG, and you're getting unexpected orientation errors as a result? Or is it possible we fixed this inadvertently? (It' been known to happen!)

Here's the link to the latest development version; I'm wondering if you could quickly look to see if it's been fixed for you.

https://cloud.ccd.pitt.edu/latest-dev-tetrad.html

**Comment by jdramsey** [comment] 2018-01-31 21:09
@espinoj I think this graph comparison issue is actually doing the right thing now, but I sent a message to Frederick for more input.

**Comment by eberharf** [comment] 2018-02-01 18:49
Looks good -- I am unable to reconstruct the problem in this development version. I can still construct it in the older version, but no need to worry about that.

**Comment by jdramsey** [comment] 2018-02-01 19:05
@eberharf @espinoj Great! Jeremy, I move we close this issue.

**Closed** 2018-02-04 13:55 UTC
