### ISSUE TITLE
default SEM BIC for continuous data as an independence test vs. fisher z for PC.

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#821] opened 2018-06-13 15:35 UTC
SEM BIC for continuous data as an independence test vs. fisher z for PC.

**Comment by jdramsey** [comment] 2019-04-11 08:19
@yuanzhou @espinoj I'm trying this in the interface right now and Fisher Z seems to be doing better than SEM BIC! SEM BIC seems to be off, not sure why; I'll look at it. In any case, Fisher Z seems the better default!

**Comment by jdramsey** [comment] 2019-04-11 08:33
@yuanzhou @espinoj Yep, unless things change, this adjustment shouldn't definitely not be done. For PC Variants, Fisher Z should be the default, as it currently is. I'll try to figure out what the issue is.

So think this one is...won't fix.

**Closed** 2019-08-01 01:30 UTC
Labels: Joe'sRec

**Comment by jdramsey** [comment] 2019-08-17 16:59
Just a note; with the new covariance calculation @kvb2univpitt did, for GES, SEM BIC score always beats Fisher Z Score the best and for constraint-based, Fisher Z test always beats SEM BIC test, so the worse test and score are removed in Tetrad 7.
