### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by ko56** [cmu-phil/tetrad#80] opened 2015-12-03 15:34 UTC
I'm a new user of Tetrad V.  The program is very impressive, but its usability would benefit greatly from some attention to the manual (new_manual.pdf).   To begin with, separate the material into sections and add a table of contents, all with hyperlinks.

Thanks very much.

**Comment by jdramsey** [comment] 2015-12-03 16:55
We're actually planning to incorporate the manual into the GitHub wiki,
with hyperlinks. Stay tuned.

Best,

Joe

On Thu, Dec 3, 2015 at 10:34 AM, ko56 <notifications@github.com> wrote:

> I'm a new user of Tetrad V. The program is very impressive, but its
> usability would benefit greatly from some attention to the manual
> (new_manual.pdf). To begin with, separate the material into sections and
> add a table of contents, all with hyperlinks.
>
> Thanks very much.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/80>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by ko56** [comment] 2015-12-03 17:17
Great, thank you.  Looking forward to it.
Regards,

                         Kostas

**Comment by jdramsey** [comment] 2015-12-24 19:55
Actually this is not on my list--it's on someone else's. :) "Won't fix"ing for now.

**Closed by jdramsey** 2015-12-24 19:55 UTC
Labels: enhancement

**Comment by ko56** [comment] 2016-01-05 16:11
I'm a little confused.   Since issue #80 is now closed, does this mean 
nothing is being done about it?  Or is the issue still open under a 
different name/number?

                             Kostas

**Comment by jdramsey** [comment] 2016-01-05 16:20
At the moment nothing is being done about it. I did my best. I'm personally
not able to address it right now. If I see some progress on it I'll re-open
it.

Maybe write to Clark Glymour (cg09@andrew.cmu.edu). He doesn't follow this
list. I've already brought it up several times and am giving up for now.

Joe

On Tue, Jan 5, 2016 at 11:11 AM, ko56 <notifications@github.com> wrote:

> I'm a little confused. Since issue #80 is now closed, does this mean
> nothing is being done about it? Or is the issue still open under a
> different name/number?
>
> Kostas
>
> On 12/24/2015 14:55, Joseph Ramsey wrote:
> >
> > Actually this is not on my list--it's on someone else's. :) "Won't
> > fix"ing for now.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cmu-phil/tetrad/issues/80#issuecomment-167154557>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/80#issuecomment-169046818>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by ko56** [comment] 2016-01-05 17:11
Ok, I don't want to make a big fuss about it.   Thanks for your efforts.
As I said at the beginning of this conversation,  a decent user manual 
makes a good impression.

                         Kostas

**Comment by jdramsey** [comment] 2016-01-05 17:33
I'll forward the message again, but I can't promise anything. I'm more interested in things other than making a good impression at the moment, like correctness and fulfilling the requirements of a grant we're on. Maybe once I'm up to speed with that stuff I can come back to trying to make a good impression. :)

Thanks for the valient effort. :)

**Comment by ko56** [comment] 2016-01-05 18:02
Just to clarify, what I really meant by 'good impression' is that if one 
is looking at selecting a tool from among a number of comparable tools, 
the documentation is a factor.

**Comment by jdramsey** [comment] 2016-01-05 18:44
I understand. The motivation is there, although not for me. Perhaps someone
will take up the cause; this is supposed to be an open source project,
though I seem to be the only person working on it (except for grad students
and the grant-related aspects). Can anyone out there help out?

Thanks,

Joe

On Tue, Jan 5, 2016 at 1:02 PM, ko56 <notifications@github.com> wrote:

> Just to clarify, what I really meant by 'good impression' is that if one
> is looking at selecting a tool from among a number of comparable tools,
> the documentation is a factor.
>
> On 01/05/2016 12:33, Joseph Ramsey wrote:
> >
> > I'll forward the message again, but I can't promise anything. I'm more
> > interested in things other than making a good impression at the
> > moment, like correctness and fulfilling the requirements of a grant
> > we're on. Maybe once I'm up to speed with that stuff I can come back
> > to trying to make a good impression. :)
> >
> > Thanks for the valient effort. :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cmu-phil/tetrad/issues/80#issuecomment-169073638>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/80#issuecomment-169083392>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by ko56** [comment] 2016-01-05 20:38
Well, I'd be willing to spend an hour on it, just to add section titles 
and hyperlinks, and a table of contents.
How does that sound?

**Comment by jdramsey** [comment] 2016-01-05 20:46
That would be most appreciated. Thanks!

On Tue, Jan 5, 2016 at 3:38 PM, ko56 <notifications@github.com> wrote:

> Well, I'd be willing to spend an hour on it, just to add section titles
> and hyperlinks, and a table of contents.
> How does that sound?
>
> On 01/05/2016 13:44, Joseph Ramsey wrote:
> > I understand. The motivation is there, although not for me. Perhaps
> > someone
> > will take up the cause; this is supposed to be an open source project,
> > though I seem to be the only person working on it (except for grad
> > students
> > and the grant-related aspects). Can anyone out there help out?
> >
> > Thanks,
> >
> > Joe
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/80#issuecomment-169126119>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by ko56** [comment] 2016-01-05 20:52
Good.  But how do I get the source?  I assume it's a Word document?

                         Kostas

**Comment by jdramsey** [comment] 2016-01-05 20:59
I'll put you in touch with the person who were working on it before. (It
wasn't me.)

Madelyn, could you send this kind person the Word file for the manual so
they can add a table of contents and hyperlinks? They have kindly offered
to help! :)

Joe

On Tue, Jan 5, 2016 at 3:52 PM, ko56 <notifications@github.com> wrote:

> Good. But how do I get the source? I assume it's a Word document?
>
> Kostas
>
> On 01/05/2016 15:46, Joseph Ramsey wrote:
> > That would be most appreciated. Thanks!
> >
> > On Tue, Jan 5, 2016 at 3:38 PM, ko56 <notifications@github.com> wrote:
> >
> > > Well, I'd be willing to spend an hour on it, just to add section titles
> > > and hyperlinks, and a table of contents.
> > > How does that sound?
> > >
> > >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/80#issuecomment-169130235>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment] 2016-01-06 13:59
Sorry, it looks like help is not available for this, and I don't have the Word document for the manual. Looks like a dead issue still. Thanks for the offer of help though!

**Comment by jdramsey** [comment] 2016-01-08 01:35
Oops, I'm being impatient. If you send me your email address, to jdramsey@andrew.cmu.edu, I'll pass it along, and have the Word document sent to you. Sorry for the hastle, just trying getting overwhelmed a little is all.
