### ISSUE TITLE
Problem from the CCD helpdesk: Discretizer error message

### ISSUE THREAD

**Issue by ccd-helpdesk** [cmu-phil/tetrad#685] opened 2018-01-19 20:20 UTC
@jdramsey @espinoj 

Hi, regarding the previous problem reported via the CCD-Helpdesk. This is a follow-up

Hello,

For every search I try in this new version [the version that @espinoj send in an attachment] of Tetrad:

![image](https://user-images.githubusercontent.com/24483727/35169906-4324315e-fd2c-11e7-9ab3-97a6455224b0.png)

Thanks

CCD-helpdesk

**Comment by cabal-cmu** [comment] 2018-01-23 19:10
@espinoj @jdramsey 

Any advances with respect to this problem ?

**Comment by espinoj** [comment] 2018-01-23 19:12
Can you describe the steps to you performed?  I'm unable to replicate.

**Comment by jdramsey** [comment] 2018-01-23 19:17
I also am unable to replicate.

**Comment by cabal-cmu** [comment] 2018-01-25 14:52
Here is more information from the user. He sent the following screenshots. He says he is working with mixed data.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/32989853/35394288-605ebe3c-01b5-11e8-92c5-8a24a13664f9.png">

<img width="982" alt="image" src="https://user-images.githubusercontent.com/32989853/35394294-6c24f54c-01b5-11e8-85ac-6e4fa957c60a.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/32989853/35394305-73bedc00-01b5-11e8-86f4-90b9446fd5ee.png">

**Comment by yuanzhou** [comment] 2018-01-25 15:13
I tried a mixed dataset with knowledge (Tiers and Edges) and did a FGES search with the same parameters but didn't see this error message. It gave me the graph.

This error message is coded in `Discretizer`.

**Comment by cabal-cmu** [comment] 2018-01-25 15:38
@yuanzhou  Thanks, 

The user is using this version. Maybe that is the problem.

 https://cloud.ccd.pitt.edu/nexus/content/repositories/snapshots/edu/cmu/tetrad-gui/6.4.0-SNAPSHOT/tetrad-gui-6.4.0-20180117.233751-169-launch.jar

**Comment by yuanzhou** [comment] 2018-01-25 18:47
I think the Tetrad jar is fairly recent and I can't reproduce that error using this jar. We really need to know the dataset and actual steps that led to this error.

**Comment by espinoj** [comment] 2018-01-25 19:32
@cabal-cmu can the user provide their session file?  Then we can see what parameters are messing up the discretizer

**Comment by cabal-cmu** [comment] 2018-01-26 17:05
@espinoj @jdramsey @yuanzhou 

Ok, so I talked to the user and he told me that he cannot share the data. That he will try to reproduce the error using simulate data.

This pose a question. When a user has a problem and she cannot share data due to privacy restrictions, what would be an alternative to extract information from the problem. Is there a log file that users can easily extract and save ?

**Comment by espinoj** [comment] 2018-01-26 17:11
errors are logged to the console so if the user executes tetrad via command line they can send us any console output

**Comment by jdramsey** [comment] 2019-08-21 17:24
No more information seems to be forthcoming on this issue; and we can't reproduce the error using our own attempts. Closing for now. If more information comes in, please re-open.

**Closed by jdramsey** 2019-08-21 17:24 UTC
