### ISSUE TITLE
6.5.2 algorithm selection

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#927] opened 2018-10-23 15:20 UTC
When I select "PC ALL" I get an FGES interface.  See attached.

Clark
<img width="821" alt="screen shot 2018-10-23 at 11 15 27 am" src="https://user-images.githubusercontent.com/16354745/47371274-84309080-d6b5-11e8-85c5-9b47908c93bf.png">
<img width="821" alt="screen shot 2018-10-23 at 11 15 27 am" src="https://user-images.githubusercontent.com/16354745/47371302-8db9f880-d6b5-11e8-8baf-5a4e46b21b9a.png">

**Comment by espinoj** [comment] 2018-11-08 18:41
seems to be resolved in 6.5.4 and in development

**Comment by kvb2univpitt** [comment] 2018-11-14 16:50
Clark, when you click the "Choose Algorithm" back button, do you see "PC All" selected in the algorithm box?

**Comment by yuanzhou** [comment] 2018-11-14 16:56
I just tested and it has been addressed in 6.5.4 branch.

**Comment by yuanzhou** [comment] 2018-11-14 17:01
I also tested the 6.5.2 both the branch code and the released version. Couldn't reproduce this error. Is it possible that Clark was using a different version or a version with customized changes?

**Comment by cg09** [comment] 2018-11-14 17:40
No, BPC is highlighted.  Clark

**Comment by cg09** [comment] 2018-11-14 17:41
I was using the version just (as in yesterday) downloaded from the  CCD
webpage link.

Clark

**Comment by cg09** [comment] 2018-11-14 20:10
Must be me. Sorry for wasting your time.

**Comment by espinoj** [comment] 2018-11-30 18:19
see #936

**Closed by espinoj** 2018-11-30 18:19 UTC
